# COLORS USED

LIGHT_BLUE  =   '#0E95EB'
LIGHT_RED   =   '#E3242B'
LIGHT_GRAY  =   '#D3D3D3'
DARK_GRAY   =   '#5A5A5A'
LIGHT_GREEN =   '#32CD32'
WHITE       =   '#FFFFFF'
BLACK       =   '#000000'

WIDTH = 850
HEIGHT = 450

FPS = 60
BOARDER_THICK = 5
CELL_SIZE = 40
CELL_NUMBER = 9
GAP = 1

FONT_NAME = 'freesansbold.ttf'
FONT_SIZE = 32

offset = 50
yMARGIN = offset//2
xMARGIN = int((HEIGHT-(CELL_NUMBER*CELL_SIZE))//2)

BUTTON_SIZE = 60
BUTTON_GAP = 10
BUTTON_BORDER = 3
BUTTON_X_MARGIN = (CELL_NUMBER*CELL_SIZE)+(offset*2)
